### ISSUE TITLE
'Missing required key 'Key' in params' when attempting to stream files to S3.

### ISSUE THREAD

**Issue by mtnptrsn** [adonisjs/adonis-drive#9]
I am trying to stream files to S3. I have disabled automatic file processing for the route I am using. I have configured s3 correctly (I know this since I am able to stream filis via adonis repl). 

This is how my controller looks like: (exactly like the demo)
```
const Drive = use('Drive')

Route.post('upload', async ({ request }) => {

  request.multipart.file('profile_pic', {}, async (file) => {
    await Drive.disk('s3').put(file.fileName, file.stream)
  })

  await request.multipart.process()
})
```

But I am getting this error from the server: 'Missing required key 'Key' in params'

Am I doing something wrong?

**Comment by SkrabakL** [comment]
Can you check while debugging if the file.fileName has a value ? Basically missing `Key` is in this bit of the code that Drive relies on 

```
 /**
   * Create a new file from string or buffer
   *
   * @method put
   * @async
   *
   * @param  {String} location
   * @param  {String} content
   * @param  {Object} [params]
   *
   * @return {Promise<String>}
   */
  put (location, content, params) {
    return new Promise((resolve, reject) => {
      const clonedParams = Object.assign({}, params, {
        Key: location,
        Body: content,
        Bucket: this._bucket.pull()
      })

      this.s3.upload(clonedParams, (error, response) => {
        if (error) {
          return reject(error)
        }
        resolve(response.Location)
      })
    })
  }
```

which means the first argument going into this put function on the `node-flydrive` driver for S3 should be there otherwise S3 throws exception and that gets thrown to you as Key missing. 
So it might not be an issue with @adonisjs/Drive itself. 

https://github.com/Slynova-Org/node-flydrive
https://github.com/Slynova-Org/node-flydrive/blob/develop/src/Drivers/AwsS3.js

**Comment by antwaanvh** [comment]
👋 @mtnptrsn 
Try using `file.clientName` instead of `file.fileName` that should work.
[Appears to be a typo in the docs.](https://github.com/adonisjs/docs/pull/252)

**Comment by thetutlage** [comment]
Closing since not actionable
